1. Importing Pandas Library

In [1]:
import pandas as pd

2. Loading Cleaned Dataset and Checking Dataset

In [3]:
df = pd.read_csv("study_abroad.csv")

In [4]:
df.columns

Index(['Year', 'Country', 'Number_of_Indian_Students', 'Tuition_Fee_USD',
       'Living_Cost_USD', 'Average_Rent_USD', 'Transportation_Cost_USD',
       'Total_Annual_Cost_USD', 'Student_Visa_Applications',
       'Student_Visa_Approvals', 'Student_Visa_Rejections',
       'Visa_Acceptance_Rate', 'Average_Graduate_Salary_USD',
       'Graduate_Employment_Rate', 'Post_Study_Work_Visa_Months',
       'PR_Availability', 'Number_of_Top_Universities', 'Average_QS_Ranking',
       'Scholarships_Available', 'GDP_Per_Capita_USD', 'Inflation_Rate'],
      dtype='object')

In [5]:
df.head()

,Year,Country,Number_of_Indian_Students,Tuition_Fee_USD,Living_Cost_USD,Average_Rent_USD,Transportation_Cost_USD,Total_Annual_Cost_USD,Student_Visa_Applications,Student_Visa_Approvals,...,Visa_Acceptance_Rate,Average_Graduate_Salary_USD,Graduate_Employment_Rate,Post_Study_Work_Visa_Months,PR_Availability,Number_of_Top_Universities,Average_QS_Ranking,Scholarships_Available,GDP_Per_Capita_USD,Inflation_Rate
0,2016,Canada,80006,24024,13024,6157,785,37048,89265,76747,...,85.98,86469,85.3,48,Yes,3,67,60,48495,4.54
1,2017,Canada,81896,19031,18746,6111,1419,37777,89807,80909,...,90.09,28425,91.2,24,No,23,162,44,46221,8.16
2,2018,Canada,87253,12078,17449,4084,1235,29527,98611,82552,...,83.71,80895,71.2,48,Yes,26,60,146,56427,7.14
3,2019,Canada,92363,29700,11300,3639,593,41000,102150,90877,...,88.96,33229,93.9,12,No,19,252,98,39319,3.46
4,2020,Canada,91405,23496,7339,5303,1593,30835,101897,71394,...,70.06,52867,77.6,24,No,55,48,63,22207,6.94

3. Creating ROI Score Column

In [6]:
df["ROI"] = (df["Average_Graduate_Salary_USD"]/df["Total_Annual_Cost_USD"])

In [9]:
df.columns

Index(['Year', 'Country', 'Number_of_Indian_Students', 'Tuition_Fee_USD',
       'Living_Cost_USD', 'Average_Rent_USD', 'Transportation_Cost_USD',
       'Total_Annual_Cost_USD', 'Student_Visa_Applications',
       'Student_Visa_Approvals', 'Student_Visa_Rejections',
       'Visa_Acceptance_Rate', 'Average_Graduate_Salary_USD',
       'Graduate_Employment_Rate', 'Post_Study_Work_Visa_Months',
       'PR_Availability', 'Number_of_Top_Universities', 'Average_QS_Ranking',
       'Scholarships_Available', 'GDP_Per_Capita_USD', 'Inflation_Rate',
       'ROI'],
      dtype='object')

In [11]:
df.head()

,Year,Country,Number_of_Indian_Students,Tuition_Fee_USD,Living_Cost_USD,Average_Rent_USD,Transportation_Cost_USD,Total_Annual_Cost_USD,Student_Visa_Applications,Student_Visa_Approvals,...,Average_Graduate_Salary_USD,Graduate_Employment_Rate,Post_Study_Work_Visa_Months,PR_Availability,Number_of_Top_Universities,Average_QS_Ranking,Scholarships_Available,GDP_Per_Capita_USD,Inflation_Rate,ROI
0,2016,Canada,80006,24024,13024,6157,785,37048,89265,76747,...,86469,85.3,48,Yes,3,67,60,48495,4.54,2.333972
1,2017,Canada,81896,19031,18746,6111,1419,37777,89807,80909,...,28425,91.2,24,No,23,162,44,46221,8.16,0.752442
2,2018,Canada,87253,12078,17449,4084,1235,29527,98611,82552,...,80895,71.2,48,Yes,26,60,146,56427,7.14,2.739696
3,2019,Canada,92363,29700,11300,3639,593,41000,102150,90877,...,33229,93.9,12,No,19,252,98,39319,3.46,0.810463
4,2020,Canada,91405,23496,7339,5303,1593,30835,101897,71394,...,52867,77.6,24,No,55,48,63,22207,6.94,1.714513

4. Creating Visa Success Score

In [18]:
df["Visa_Success"] = (df["Student_Visa_Approvals"] / df["Student_Visa_Applications"]) * 100

In [16]:
df.columns

Index(['Year', 'Country', 'Number_of_Indian_Students', 'Tuition_Fee_USD',
       'Living_Cost_USD', 'Average_Rent_USD', 'Transportation_Cost_USD',
       'Total_Annual_Cost_USD', 'Student_Visa_Applications',
       'Student_Visa_Approvals', 'Student_Visa_Rejections',
       'Visa_Acceptance_Rate', 'Average_Graduate_Salary_USD',
       'Graduate_Employment_Rate', 'Post_Study_Work_Visa_Months',
       'PR_Availability', 'Number_of_Top_Universities', 'Average_QS_Ranking',
       'Scholarships_Available', 'GDP_Per_Capita_USD', 'Inflation_Rate', 'ROI',
       'Visa_Success'],
      dtype='object')

In [17]:
df.head()

,Year,Country,Number_of_Indian_Students,Tuition_Fee_USD,Living_Cost_USD,Average_Rent_USD,Transportation_Cost_USD,Total_Annual_Cost_USD,Student_Visa_Applications,Student_Visa_Approvals,...,Graduate_Employment_Rate,Post_Study_Work_Visa_Months,PR_Availability,Number_of_Top_Universities,Average_QS_Ranking,Scholarships_Available,GDP_Per_Capita_USD,Inflation_Rate,ROI,Visa_Success
0,2016,Canada,80006,24024,13024,6157,785,37048,89265,76747,...,85.3,48,Yes,3,67,60,48495,4.54,2.333972,85.976587
1,2017,Canada,81896,19031,18746,6111,1419,37777,89807,80909,...,91.2,24,No,23,162,44,46221,8.16,0.752442,90.092086
2,2018,Canada,87253,12078,17449,4084,1235,29527,98611,82552,...,71.2,48,Yes,26,60,146,56427,7.14,2.739696,83.714799
3,2019,Canada,92363,29700,11300,3639,593,41000,102150,90877,...,93.9,12,No,19,252,98,39319,3.46,0.810463,88.964268
4,2020,Canada,91405,23496,7339,5303,1593,30835,101897,71394,...,77.6,24,No,55,48,63,22207,6.94,1.714513,70.064869

5. Creating Affordability Score Column

In [19]:
df["Affordability"] = (1/df["Total_Annual_Cost_USD"]) * 100000

In [20]:
df.columns

Index(['Year', 'Country', 'Number_of_Indian_Students', 'Tuition_Fee_USD',
       'Living_Cost_USD', 'Average_Rent_USD', 'Transportation_Cost_USD',
       'Total_Annual_Cost_USD', 'Student_Visa_Applications',
       'Student_Visa_Approvals', 'Student_Visa_Rejections',
       'Visa_Acceptance_Rate', 'Average_Graduate_Salary_USD',
       'Graduate_Employment_Rate', 'Post_Study_Work_Visa_Months',
       'PR_Availability', 'Number_of_Top_Universities', 'Average_QS_Ranking',
       'Scholarships_Available', 'GDP_Per_Capita_USD', 'Inflation_Rate', 'ROI',
       'Visa_Success', 'Affordability'],
      dtype='object')

In [21]:
df.head()

,Year,Country,Number_of_Indian_Students,Tuition_Fee_USD,Living_Cost_USD,Average_Rent_USD,Transportation_Cost_USD,Total_Annual_Cost_USD,Student_Visa_Applications,Student_Visa_Approvals,...,Post_Study_Work_Visa_Months,PR_Availability,Number_of_Top_Universities,Average_QS_Ranking,Scholarships_Available,GDP_Per_Capita_USD,Inflation_Rate,ROI,Visa_Success,Affordability
0,2016,Canada,80006,24024,13024,6157,785,37048,89265,76747,...,48,Yes,3,67,60,48495,4.54,2.333972,85.976587,2.699201
1,2017,Canada,81896,19031,18746,6111,1419,37777,89807,80909,...,24,No,23,162,44,46221,8.16,0.752442,90.092086,2.647113
2,2018,Canada,87253,12078,17449,4084,1235,29527,98611,82552,...,48,Yes,26,60,146,56427,7.14,2.739696,83.714799,3.386731
3,2019,Canada,92363,29700,11300,3639,593,41000,102150,90877,...,12,No,19,252,98,39319,3.46,0.810463,88.964268,2.439024
4,2020,Canada,91405,23496,7339,5303,1593,30835,101897,71394,...,24,No,55,48,63,22207,6.94,1.714513,70.064869,3.243068

6. Saving the Dataset After Applying Featured Engineering

In [7]:
df.to_csv("study_abroad_features.csv",index=False)

In [8]:
print("Feature Engineering Completed!")

Feature Engineering Completed!